### ISSUE TITLE
 Understanding WebRTC

### ISSUE THREAD

**Issue by Colintsl** [freddyaboulton/gradio-webrtc#34]
Hi
**1.**  I would like to confirm whether this component is designed to facilitate the real-time frame-by-frame display of videos on web pages, as opposed to the gr.Video() component which requires the entire video to be uploaded beforehand.
**2.**  In the context of the `video_out_stream.py` script, I am curious if it is possible to replace the following line with a local video path.：

`url = "https://download.tsi.telecom-paristech.fr/gpac/dataset/dash/uhd/mux_sources/hevcds_720p30_2M.mp4";`

I have attempted to do so and encountered an error message indicating that the file could not be found with the provided mode. The local URL is running on http://127.0.0.1:7860, and I am informed that to create a public link, I should set share=True in the launch() function. 
I have ensured that the local path I provided for the video file is correct, and I am confident there are no issues with the path itself.

I would appreciate any guidance on how to properly configure the WebRTC component to stream video from a local file path, or if there are any limitations or specific requirements I should be aware of.

Thank you in advance for your assistance. I look forward to your response and am excited to further explore the capabilities of Gradio.

Best regards,
Colintsl

**Comment by freddyaboulton** [comment]
Hi @Colintsl ! 

Yes, you can replace that URL with a local video file. Probably that error is related to Gradio not being able to access that file due to security reasons. If you place the video in the same working directory as your app file or add it in `allowed_paths` parameter of `launch` it should work.

If it does not please share a minimal reproducer.
